### ISSUE TITLE
Switch to http-client

### ISSUE THREAD

**Issue by elliottt** [elliottt/hsopenid#11]
It would be great to move away from the HTTP library, and use http-client instead, as it allows for much simpler SSL integration.

**Comment by Akii** [comment]
Hi! I just needed this as well. Why did you close the issue?


Edit: Here is my super ugly work-around.
```
mapRequest :: MonadThrow m => HTTP.Request String -> m Request
mapRequest r = do
  initReq <- parseRequest uri
  return
    initReq
    { method = "POST"
    , requestHeaders = [("Content-Type", "application/x-www-form-urlencoded")]
    , requestBody = RequestBodyBS (fromString payload)
    }
  where
    uri = show $ HTTP.rqURI r
    payload = HTTP.rqBody r

mapResponse
  :: Response LBS.ByteString
  -> HTTP.Result (HTTP.Response String)
mapResponse res =
  if code /= status200
    then HTTP.failMisc ("Bad Status Code" <> show res)
    else Right
           HTTP.Response
           { HTTP.rspCode = (2, 0, 0)
           , HTTP.rspReason = "What tf is this even?"
           , HTTP.rspBody = body
           , HTTP.rspHeaders = mempty
           }
  where
    code = responseStatus res
    body = LBS.unpack $ responseBody res
```

**Comment by elliottt** [comment]
It didn't seem like the library was getting much use, so I decided that it was a lower priority. If you'd like to work on it, I'd be happy to merge in your work :)

**Comment by Akii** [comment]
Oh boy, I had no idea what I was getting myself into!

So my use-case was that I needed to use SSL. Which I just now found out you apparently have a custom implementation of? Not so sure tbh. Anyhow this is the work in progress. The really interesting part is a rather small change to the Resolver:

https://github.com/Akii/hsopenid/commit/d65d6846a48a08ba4a91de3e6219d946f4a774d4#diff-5bd399c843e41395c83f0279e3853db1R110

Even disregard the type of the Resolver atm. What's important is that I use http-types to build two basic record types: Request and Response. Those will be stripped down to what the library actually needs to do (uri, method, headers, string-like body).

Do you find this approach agreeable? I must confess I'm really not into reading the OpenID RFC at this time and I'm just juggling types with a rather basic understanding.

**Comment by elliottt** [comment]
Seems reasonable to me. One thing that would be nice is keeping to bytestring/text-like strings for the request body. From what I remember, there were problems with the HTTP library there, so maybe switching away from it resolves that problem.

**Comment by Akii** [comment]
I just defaulted it to lazy bytestring for now. I'll at least get this to run with HTTP, Wreq and http-client.
