### ISSUE TITLE
Build errors Network.URI and unsafePerformIO

### ISSUE THREAD

**Issue by promi** [elliottt/hsopenid#13]
Hi,

I have tried to build openid and got to build problems:

src/Network/OpenID/Authentication.hs:35:8:
    Could not find module ‘Network.URI’
    It is a member of the hidden package ‘network-uri-2.6.0.3’.
    Perhaps you need to add ‘network-uri’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.

[11 of 17] Compiling Data.Digest.OpenSSL.SHA ( src/Data/Digest/OpenSSL/SHA.hs, dist/build/Data/Digest/OpenSSL/SHA.o )

src/Data/Digest/OpenSSL/SHA.hs:26:8:
    Not in scope: ‘unsafePerformIO’

src/Data/Digest/OpenSSL/SHA.hs:32:10:
    Not in scope: ‘unsafePerformIO’

I have tried to fix both problems:

https://gist.github.com/promi/596ce61dd824f27a28d9

**Comment by elliottt** [comment]
I think that these errors should be resolved in version 0.2.1.0. Sorry for the incredibly long delay!
